---
title: "How do Certain Factors Affect the Ratings of Boardgames?"
subtitle: "Too Legit to Overfit"
author: "Archie Cannon, Arjun Nanning Ramamurthy, Bruce McPhail, Connor Williams"
institute: "University of Edinburgh"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      countIncrementalSlides: false
---

```{r load-packages, include = FALSE}
library(tidyverse)
library(tidymodels)
library(knitr)
library(here)
library(xaringanthemer)
library(scales)
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.retina = 3, dpi = 300, fig.width = 6, fig.asp = 0.618, out.width = "80%")
```

```{r r-squared, echo = FALSE}
display_r_squared <- function(fit) {
  paste0(
    "$$R^2=",
    round(glance(fit)$r.squared[1], 3),
    ",R_{adj}^2=",
    round(glance(fit)$adj.r.squared[1], 3),
    ".$$"
  )
}
```

```{r load-data, include = FALSE}
board_games <- read_csv(here("data/board_games.csv"))
```

```{r glimpse, echo = FALSE}
glimpse(board_games)
```

---

# Categories

```{r popular-categories, echo = FALSE}
board_games_splitcats <- board_games %>% 
  mutate(categories = str_split(category, ","))

popular_categories <- board_games_splitcats %>%
  pull(categories) %>%
  unlist %>%
  as_tibble %>%
  count(value) %>%
  arrange(desc(n)) %>%
  head(6)

popular_categories %>%
  knitr::kable()

popular_categories <- pull(popular_categories, value)
```

---
```{r filter-top-cats-alt, echo = FALSE, warning = FALSE}
board_games_topcats <- board_games_splitcats %>% 
  filter(map_lgl(categories, ~any(popular_categories %in% .x)))
```
```{r top-cats-over-time, message = FALSE, warning = FALSE, echo = FALSE}
av_annual_rating <- function(df, cat = NULL) {
  {if(!is.null(cat)) {
    df %>% filter(map_lgl(categories, ~cat %in% .x))
  } else {
    df
  }} %>% 
  group_by(year_published) %>% 
  summarise(av_annual_rating = sum(average_rating * users_rated) / sum(users_rated))
}
# finds average rating (of a category (cat) if given) of board games in dataframe given (df) for each year in which a board game of that category was published. Output is a dataframe. df must have columns `year published`, `categories` (a `list` of categories), `average_rating` and `year_published`. 

cats <- map(popular_categories, ~av_annual_rating(df = board_games_topcats, cat = .))

cat_ratings <- reduce(cats, ~full_join(.x,.y, by = "year_published")) %>% 
  arrange(year_published)

if(any(is.na(popular_categories))) {
  popular_categories[[which(is.na(popular_categories))]] <- "not_categorised"
} 

names(cat_ratings) <- c("year_published", popular_categories)
```

```{r top-cats-over-time-plot, warning = FALSE, echo = FALSE, message = FALSE}
cat_ratings %>% 
  pivot_longer(cols = 2:ncol(cat_ratings), names_to = "category", values_to = "av_rating") %>% 
  ggplot(aes(x = year_published, y = av_rating, colour = category)) + 
  geom_line() +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~ category) +
  labs(
    x = "Year published", 
    y = "Mean annual category rating", 
    colour = "Category",
    title = "Average ratings plotted over year published",
    subtitle = "Faceted by the 6 most popular categories"
  ) + 
  scale_color_viridis_d() +
  theme_minimal()
```
---

```{r yeet, echo = FALSE, warning = FALSE, message = FALSE}
board_games_empty <- board_games_splitcats %>%
  filter(FALSE)
board_games_popcats <- board_games_empty

for (c in popular_categories) {
  board_games_popcats <- full_join(
    board_games_popcats,
    board_games_splitcats %>%
      filter(map_lgl(categories, ~c %in% .x)) %>%
      mutate(category = c)
  )
}

cat_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(average_rating ~ category, data = board_games_popcats)

cat_fit_aug <- augment(cat_fit$fit)

ggplot(cat_fit_aug, mapping = aes(x = .fitted, y = .resid)) +
  geom_point(alpha = 0.5, aes(color = category)) +
  geom_hline(yintercept = 0, color = "gray", lty = "dashed") +
  labs(x = "Predicted rating", y = "Residuals",
       title = "Plot of the residuals using only the 6 categories") +
  theme_minimal()
```

Note that each of these vertical lines represents one of the 6 categories
---

```{r looking-at-rsquared, echo = FALSE}
tidy(cat_fit)
```

---

# Year published

```{r year-published-rating, echo = FALSE, message = FALSE}
board_games %>%
  group_by(year_published) %>%
  summarise(rating = mean(average_rating)) %>%
  ggplot(aes(
    x = year_published,
    y = rating
  )) +
  geom_line() +
  theme_minimal() +
  labs(
    x = "Year Published",
    y = "Rating"
  )
```

---

```{r year-published-rating-fit, echo = FALSE}
year_published_rating_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(average_rating ~ year_published, data = board_games)
```

```{r year-published-rating-line, echo = FALSE, message = FALSE}
board_games %>%
  group_by(year_published) %>%
  summarise(rating = mean(average_rating)) %>%
  ggplot(aes(
    x = year_published,
    y = rating
  )) +
  geom_line() +
	geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(
    x = "Year Published",
    y = "Rating"
  )
```

`r display_r_squared(year_published_rating_fit)`

---

# Playing time
```{r first_plot, echo = FALSE}
board_games %>%
  filter(playing_time != 0) %>%
  ggplot(aes(playing_time, average_rating)) +
  geom_point(alpha = 0.6) +
  scale_x_log10(labels = format_format(scientific = FALSE)) +
  xlim(NA, 11000) +
  theme_minimal() +
  labs(title = "Average rating against average playing time", x = "Avergage playing time", y = "Average Rating") 
```

```{r archie_set-up, include = FALSE}
board_games <- board_games %>%
  filter(playing_time != 0, min_playtime != 0)

set.seed(1116)

games_split <- initial_split(board_games, prop = 0.8)
train_data <- training(games_split)
test_data <- testing(games_split) 

games_lm_mod <- linear_reg() %>%
  set_engine("lm")

games_play_recipe <- recipe(average_rating ~ playing_time, data = train_data) %>%
  step_log(all_predictors())

games_play_workflow <- workflow() %>%
  add_model(games_lm_mod) %>%
  add_recipe(games_play_recipe)

games_play_fit <- games_play_workflow %>% 
  fit(data = train_data)

games_play_all_recipe <- recipe(
  average_rating ~ playing_time + min_playtime,
  data = train_data
  ) %>%
  step_log(all_predictors())

games_play_all_workflow <- workflow() %>%
  add_model(games_lm_mod) %>%
  add_recipe(games_play_all_recipe)

games_play_all_fit <- games_play_all_workflow %>%
  fit(data = train_data)

games_play_pred <- predict(games_play_fit, test_data) %>%
  bind_cols(test_data)

games_play_all_pred <- predict(games_play_all_fit, test_data) %>%
  bind_cols(test_data)

predict_both <- games_play_all_pred %>%
  mutate(.pred_all = .pred, .keep = "unused") %>%
  right_join(games_play_pred) %>%
  select(.pred, .pred_all, average_rating, everything())
```
---
```{r model_graph, echo = FALSE}
games_play_pred %>%
  ggplot(aes(x = playing_time)) +
  geom_point(aes(y = average_rating)) +
  geom_line(aes(y = .pred), colour = "red") +
  scale_x_log10() +
  theme_minimal() +
  labs(title = "Average rating against average playing time", x = "Average Playing Time", y = "Average Rating")
```
---

# Users rated

---

# Interesting observations

```{r popular-categories-year-published, echo = FALSE, message = FALSE}
board_games_splitcats <- board_games %>% 
  mutate(categories = str_split(category, ","))

popular_categories <- board_games_splitcats %>%
  pull(categories) %>%
  unlist %>%
  as_tibble %>%
  count(value) %>%
  arrange(desc(n)) %>%
  head(6) %>%
  pull(value)

board_games_empty <- board_games_splitcats %>%
  filter(FALSE)
board_games_popcats <- board_games_empty

for (c in popular_categories) {
  board_games_popcats <- full_join(
    board_games_popcats,
    board_games_splitcats %>%
      filter(map_lgl(categories, ~c %in% .x)) %>%
      mutate(category = c)
  )
}

board_games_popcats %>%
  group_by(category, year_published) %>%
  summarise(count = n()) %>%
  ggplot(aes(
    x = year_published,
    y = count,
    color = category
  )) +
  geom_line() +
  theme_minimal() +
  labs(
    x = "Year Published",
    y = "Number of Games",
    color = "Category"
  )
```

---

# Conclusion
