---
title: "Data"
author: "Too Legit to Overfit"
output: github_document
---

## `board_games.csv`

Each row in the dataset represents a board game on Board Game Geeks; each column represents a property of the game. The dimensions of the dataset are 10,532 x 22.

 - `game_id` - Unique game identifier
 - `description` - A paragraph of text describing the game
 - `image` - URL image of the game
 - `max_players` - Maximum recommended players
 - `max_playtime` - Maximum recommended playtime (min)
 - `min_age` - Minimum recommended age
 - `min_players` - Minimum recommended players
 - `min_playtime` - Minimum recommended playtime (min)
 - `name` - Name of the game
 - `playing_time` - Average playtime (min)
 - `thumbnail` - URL thumbnail of the game
 - `year_published` - Year game was published
 - `artist` - Artist for game art
 - `category` - Categories for the game (separated by commas)
 - `compilation` - If part of a multi-compilation - name of compilation
 - `designer` - Game designer
 - `expansion` - If there is an expansion pack - name of expansion
 - `family` - Family of game - equivalent to a publisher
 - `mechanic` - Game mechanic - how game is played, separated by comma
 - `publisher` - Company/person who published the game, separated by comma
 - `average_rating` - Average rating on Board Games Geek (1-10)
 - `users_rated` - Number of users that rated the game

```{r glimpse, echo = FALSE, message = FALSE}
library(tidyverse)
board_games <- read_csv("board_games.csv")
glimpse(board_games)
```

## References

Board Game Geek 2019, _Board Games Database_, electronic dataset, Tidy Tuesdays, viewed 23 October 2020, <https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-03-12>.

Jeto N 2015, _Fitting Distributions_, University of Lisbon, viewed 22 Nov 2020, <http://www.di.fc.ul.pt/~jpn/r/distributions/fitting.html>

Sauer S 2017, _Simple way of plotting normal/logistic/etc. curve_, sebastiansauer.github.io, viewed 22 Nov 2020, <https://sebastiansauer.github.io/plotting_s-curve/>
